[project]
name = "shadow-clone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
test = [
    "httpx>=0.28.1",
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
]

[tool.uv.workspace]
members = [
    "backend",
]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
